services:
  prometheus:
    build:
      context: ./prometheus
    image: fcg-prometheus:1.0.0
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    build:
      context: ./grafana
    image: fcg-grafana:1.0.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/fcgames-observability.json
    depends_on:
      - prometheus

