global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fcg-users-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['fcg-users-service:5001']

  - job_name: 'fcg-catalog-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['fcg-catalog-service:5002']
